<?php

/**
 * @file
 * Alters to question forms.
 */

/**
 * Implements hook_form_FORM_ID_alter
 *
 * Changes the title of the registration form
 *
 * @param $form
 * @param $form_state
 */
function prc_question_form_form_multichoice_node_form_alter(&$form, &$form_state) {
$x = 'x';

  $choice_count = $form_state['choice_count'];

//  $format = $form['alternatives'][0]['answer']['#format']; // filtered_html

  for($c = 0; $c < $choice_count; $c++) {
    $form['alternatives'][$c]['orig_answer'] = $c['alternatives'][$c]['answer'];
    $form['alternatives'][$c]['answer']['#type'] = 'textarea';
    $form['alternatives'][$c]['orig_answer']['#access'] = FALSE;
  }

  array_unshift($form['#validate'], 'prc_question_form_form_multichoice_node_form_validate');

//  $form['#validate'][] = 'prc_question_form_form_multichoice_node_form_validate';

}

function prc_question_form_form_multichoice_node_form_validate(&$form, &$form_state) {
  $x = 'x';

  $choice_count = $form_state['choice_count'];

//  $format = $form['alternatives'][0]['answer']['#format']; // filtered_html

  for($c = 0; $c < $choice_count; $c++) {
    // use form_set_value
//    $form['alternatives'][$c]['orig_answer']['#value'] = $form['alternatives'][$c]['answer']['#value'];
    $form_state['values']['node']['alternatives'][$c]['answer'] = array(
      'format' => 'filtered_html',
      'value' => 'filtered_html'
    );

  }
}

/**
 *  Implements hook_form_alter().
 */
function prc_question_form_form_alter(&$form, &$form_state, $form_id) {
  $x = 'x';
}