<?php
/**
 * @file
 * Code for the PRC Custom Modules feature.
 */

include_once 'prc_custom_modules.features.inc';

/**
 * Implements hook_date_formats().
 */
function prc_custom_modules_date_formats() {
  return array(
    // Creates a new format for use in gallery view.
    array(
      'type' => 'prc_custom_modules_date_only',
      'format' => 'F d, Y',
      'locales' => array(),
    ),
  );
}

/**
 * Implements hook_date_format_types().
 */
function prc_custom_modules_date_format_types() {
  return array(
    'prc_custom_modules_date_only' => t('Date Only: Month DD, YYYY'),
  );
}
