<?php

/**
 * @file
 * Alters to registration forms.
 */

/**
 * Implements hook_form_FORM_ID_alter
 *
 * Changes the title of the registration form
 *
 * @param $form
 * @param $form_state
 */
function prc_registration_form_user_register_form_alter(&$form, &$form_state) {

  drupal_set_title('Create User Account to Join Partnership Resource Center');
  $invite = invite_load_from_session();

  $form['#validate'][] = 'prc_registration_form_user_register_form_validate';

  $form['field_user_state']['und']['#title'] = t('State where you teach');
  //Mark the states that are PARCC in the user states dropdown
  //Make it so the account number text box appears when they are selected
  $p_states = db_query('select name from taxonomy_term_data where vid = (
      select vid from taxonomy_vocabulary where machine_name = \'member_state\')')->fetchCol('vid');
  //$form_state['p_states'] = $p_states;
  $state_field = ':input[name="field_user_state[und]"]';

  //Needed for the invite
  $original_opts = $form['field_user_state']['und']['#options'];

  foreach ($form['field_user_state']['und']['#options'] as $tid => &$term) {
    if (in_array($term, $p_states)) {
      $term = $term . ' - PARCC Member';
      $form['state_account_number']['#states']['visible'][$state_field][] = array('value' => $tid);
    }
  }

  // We don't want to display any of this stuff if the user is coming from an invite
  if (!$invite) {

    $profession_weight = $form['field_user_state']['#weight'];
    //variable to hold the selector for the state field

    $form['state_account_number'] = array(
      '#type' => 'textfield',
      '#title' => t('State Account #'),
      '#weight' => $profession_weight + 2,
      '#states' => array(
        'visible' => array(
          $state_field => array(),
        ),
        'required' => array(
          $state_field => array(),
        ),
      ),
    );
  }else{
    $form['field_user_state']['#required'] = FALSE;
    $form['field_user_state']['#access'] = FALSE;
    $w_invite = entity_metadata_wrapper('invite', $invite);
    $user_state = $w_invite->field_user_state->value();
    if ($user_state) {
      $form['text_user_state'] = array(
        '#type' => 'item',
        '#title' => t('State Where I Teach'),
        '#markup' => $user_state->name,
      );
    }
  }
  $form['#validate'][] = 'prc_registration_form_user_register_form_validate';
}

/**
 * Validate for user registration form
 *
 * @param $form
 * @param $form_state
 */
function prc_registration_form_user_register_form_validate(&$form, &$form_state) {

  $invite = invite_load_from_session();
  if ($invite) {
    if (count($invite->field_member_state)) {
      $tid = $invite->field_member_state[LANGUAGE_NONE][0]['tid'];
      $form_state['values']['field_member_state'][LANGUAGE_NONE][0]['tid'] = $tid;
    }
    if (count($invite->field_user_state)) {
      $tid = $invite->field_user_state[LANGUAGE_NONE][0]['tid'];
      $form_state['values']['field_user_state'][LANGUAGE_NONE][0]['tid'] = $tid;
    }
  }

  if (
    array_key_exists('has_member_state', $form_state['values']) && $form_state['values']['has_member_state']
  ) {

    $account_number = $form_state['values']['state_account_number'];
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'taxonomy_term')
      ->entityCondition('bundle', 'member_state')
      ->fieldCondition('field_state_code', 'value', $account_number, '=');
    $result = $query->execute();
    if (array_key_exists('taxonomy_term', $result)) {
      $tids = array_keys($result['taxonomy_term']);
      $tid = reset($tids);
      $form_state['values']['field_member_state'][LANGUAGE_NONE][0]['tid'] = $tid;
    }
    else {
      form_set_error('state_account_number', t('Valid State Account # is incorrect. Leave this blank if you do not have one.'));
    }
  }
}