<?php
/**
 * @file
 * PARCC PRC Course Views Handlers module code.
 */

/**
 * Implements hook_views_api().
 */
function prc_course_views_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'prc_course_views') . '/views',
  );
}

/**
 * Implements hook_node_view().
 */
function prc_course_views_node_view($node, $view_mode, $langcode) {
  if ($view_mode == 'full' && $node->type == 'pd_course') {
    $w = entity_metadata_wrapper('node', $node);
    $link = $w->field_link_to_a_url->value();
    if ($link) {
      $link_options = array(
        'attributes' => array(
          'class' => array('course-take-course-link'),
          'target' => '_blank',
        ),
      );
      $link = '<div class="course-take-course-link-wrapper">' . l(t('Take course'), $link['url'], $link_options) . '</div>';
      $node->content['course']['#markup'] = $link;
    }
  }
}
