<?php

/**
 * @file Hooks and configuration pertaining to the editing workflow of the PRC site.
 */

/**
 * Implements hook_permission
 *
 * @return array
 */
function prc_workflow_permission() {
  return array(
    'request approval of prc content' => array(
      'title' => t('Request Approval of PRC content'),
      'description' => t('Request that content be approved and published through the PRC workflow.'),
    ),
    'approve prc content' => array(
      'title' => t('Publish PRC content'),
      'description' => t('Approve and publish content managed through the PRC workflow.'),
    ),
    'deny prc content' => array(
      'title' => t('Deny PRC content'),
      'description' => t('Deny publishing of content managed through the PRC workflow.')
    ),
    'unpublish prc content' => array(
      'title' => t('Unpublish PRC content'),
      'description' => t('Move content managed through the PRC workflow from published back to draft'),
    ),
  );
}

/**
 * Implements hook_menu_alter()
 */
function prc_workflow_menu_alter(&$menu) {
  $menu['node/%node/edit']['access callback'] = 'prc_workflow_access';
  $menu['node/%node/revisions/%/workflow']['access callback'] = 'prc_workflow_events_revision_access';
  $menu['node/%node/revisions/%/edit']['access callback'] = 'prc_workflow_access';
  $menu['node/%node/delete']['access callback'] = 'prc_workflow_delete_access';
}

/**
 * Implements hook_menu_local_tasks_alter()
 *
 * @param $data
 * @param $router_item
 * @param $root_path
 */
function prc_workflow_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  //Add tabs to the revision pages
  $path = $router_item['path'];
  $parts = explode('/', $router_item['href']);

  switch ($path) {
    case 'node/%/revisions/%/edit' :
    case 'node/%/revisions/%/view' :
      $nid = $parts[1];
      $vid = $parts[3];
      $data['tabs'][0]['count'] = 2;
      $data['tabs'][0]['output'] = array(
        0 => array(
          '#theme' => 'menu_local_task',
          '#link' => array(
            'title' => t('View Revision'),
            'href' => "node/$nid/revisions/$vid/view",
            'localized_options' => array(),
          ),
        ),
        1 => array(
          '#theme' => 'menu_local_task',
          '#link' => array(
            'title' => t('Edit Revision'),
            'href' => "node/$nid/revisions/$vid/edit",
            'localized_options' => array(),
          ),
        )
      );
      break;
  }

  switch ($path) {
    case 'node/%/revisions/%/edit' :
      $data['tabs'][0]['output'][0]['#active'] = FALSE;
      $data['tabs'][0]['output'][1]['#active'] = TRUE;
      break;
    case 'node/%/revisions/%/view' :
      $data['tabs'][0]['output'][0]['#active'] = TRUE;
      $data['tabs'][0]['output'][1]['#active'] = FALSE;
      break;
  }

}

/**
 * Custom access check for interacting with digital library nodes
 *
 * @param $op
 * @param $node
 * @param null $account
 * @return bool
 */
function prc_workflow_access($op, $node, $account = NULL) {
  if (empty($account)) {
    global $user;
    $account = $user;
  }
  if (node_access($op, $node, $account) && $node->type == 'digital_library_content') {

    //Block access to editing for contributors when under review
    if ($op == 'update' && prc_workflow_reported_state($node->nid) === 'ready_for_review') {

      return user_access('approve prc content', $account);
    }
    else {
      return TRUE;
    }
  }
  else {
    return node_access($op, $node, $account);
  }
}

/**
 * Menu access callback for the node revision workflow transition page.
 */
function prc_workflow_events_revision_access($node, $event_name = NULL) {
  $machine = state_flow_load_state_machine($node);

  //if there is an event name base access on that, otherwise pass to state flow
  if ($event_name) {
    $event = $machine->get_event($event_name);

    return $event->validate();
  }
  else {
    return !empty($event_name) ? state_flow_access($node, $event_name) : state_flow_menu_node_access($node);
  }
}

/**
 * Block access to deleting digital library nodes
 *
 * @param $op
 * @param $node
 * @param null $account
 * @return bool
 */
function prc_workflow_delete_access($op, $node, $account = NULL){
  if (empty($account)) {
    global $user;
    $account = $user;
  }
  if ($node->type == 'digital_library_content') {
    $machine = state_flow_load_state_machine($node);

    //states that should block delete access
    $blocking_states = array('published', 'ready_for_review');
    foreach($blocking_states as $state){
      $vid = prc_workflow_fetch_latest_node_version_by_state($node->nid, $state);
      if($vid){
        //Block access if we have a result
        return FALSE;
      }
    }
  }
  return node_access($op, $node, $account);
}

/**
 * Implements hook_ctools_plugin_directory()
 *
 * @param $owner
 * @param $plugin_type
 * @return string
 */
function prc_workflow_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return "plugins/$plugin_type";
  }
}

/**
 * Implements hook_state_flow_plugins()
 */
function prc_workflow_state_flow_plugins() {
  $info = array();

  $info['prc_workflow'] = array(
    'handler' => array(
      'parent' => 'state_flow',
      'class' => 'prcWorkflow',
      'file' => 'prcWorkflow.inc',
      'path' => drupal_get_path('module', 'prc_workflow') . '/plugins',
    )
  );

  return $info;
}

/**
 * Implements hook_views_api().
 */
function prc_workflow_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'prc_workflow') . '/includes/views',
  );
}

/**
 * Implements hook_token_info()
 *
 * @return array
 */
function prc_workflow_token_info() {
  $node['workflow-comments'] = array(
    'name' => t('Workflow Comments'),
    'description' => t('Comments associated with changes in the revision state.')
  );

  $type = array(
    'name' => t('Message'),
    'description' => t('Tokens related to individual messages.'),
    'needs-data' => 'message',
  );
  return array(
    'types' => array('message' => $type),
    'tokens' => array('message' => $node),
  );
}

/**
 * Implements hook_tokens()
 * @param $type
 * @param $tokens
 * @param array $data
 * @param array $options
 * @return array
 */
function prc_workflow_tokens($type, $tokens, $data = array(), $options = array()) {
  $replacements = array();
  if ($type == 'message' && !empty($data['message'])) {
    foreach ($tokens as $name => $original) {
      $message = $data['message'];
      $m = entity_metadata_wrapper('message', $message);
      switch ($name) {
        case 'field-node:workflow-comments' :
          //Fetch the latest comment for this node revision from the db
          $node = $m->field_node->value();

          $vid = $m->field_version_id->value();

          $result = db_query('select * from {node_revision_states_history} where nid = :nid and vid = :vid order by "timestamp" DESC;',
            array(':nid' => $node->nid, ':vid' => $vid)
          );
          $history = $result->fetchAll();
          $latest = array_shift($history);
          if (!empty($latest)) {
            $replacements[$original] = check_plain($latest->log);
          }
          break;
      }
    }
  }
  return $replacements;
}


/**
 * Implements hook_state_flow_machine_type_alter()
 *
 * @param string $machine_type
 * @param object $node
 */
function prc_workflow_state_flow_machine_type_alter(&$machine_type, $node) {
  if ($node->type === 'digital_library_content') {
    $machine_type = 'prc_workflow';
  }
}

/**
 * Implements HOOK_form_FORM_ID_alter()
 */
function prc_workflow_form_digital_library_content_node_form_alter(&$form, &$form_state) {
  $node = $form['#node'];

  if (!empty($form_state['display_confirmation'])) {
    prc_workflow_draft_confirm_form($form, $form_state);
  }
  elseif (!empty($node->vid)) {
    //state flow won't work without a vid, so skip on node creation
    //Add action buttons for workflow events
    $state_flow = state_flow_load_state_machine($node);

    $action_button = array(
      '#type' => 'submit',
      '#access' => TRUE,
      '#submit' => array(
        'prc_workflow_pre_submit_handler',
        'node_form_submit',
        'prc_workflow_submit_handler'
      ),
    );

    //Find the event appropriate to the state
    $weight = -10;

    $events = $state_flow->get_available_events();

    foreach ($events as $key => $event) {
      //make sure only actions available to the user are displayed
      if ($event->validate()) {
        //use our button prototype from above and customize for the context
        $options = $event->get_options();
        $form['actions'][$key] = $action_button;
        $form['actions'][$key]['#value'] = $options['label'];
        $form['actions'][$key]['#weight'] = $weight;
        $form['actions'][$key]['#attributes'] = array('data-event' => $key);

        $weight += -3;
      }
    }

    //Change the text of the submit button to save draft
    $form['actions']['submit']['#value'] = "Save New Draft";
    //Require confirmation when in published state
    if($state_flow->get_current_state() === 'published') {
      $form['actions']['submit']['#submit'] = array('prc_workflow_pre_submit_handler');
    }

    //Hide delete button if our access callback fails
    if(isset($form['actions']['delete']) && !prc_workflow_delete_access('delete', $node)){
      unset($form['actions']['delete']);
    }
  }
  if(isset($form['revision_information'])){
    //Hide the revision vtab
    unset($form['revision_information']);
  }
}

/**
 * Helper for the confirmation form when saving a new draft
 */
function prc_workflow_draft_confirm_form(&$form, &$form_state) {
  //Unset non-field elements
  $disable = array(
    'title',
    'author',
    'menu',
    'path',
    'comment_settings',
    'actions',
    'revision_information',
    'body',
    'options'
  );

  foreach ($disable as $element) {
    if(isset($element)){
      unset($form[$element]);
    }
  }

  //unset the fields
  foreach ($form as $key => $element) {
    if (strpos($key, 'field') === 0) {
      unset($form[$key]);
    }
  }

  $form['confirm_message'] = array(
    '#prefix' => '<p>',
    '#suffix' => '</p>',
    '#markup' => t('You are about to save a new draft'),
  );

  $form['actions']['confirm'] = array(
    '#type' => 'submit',
    '#value' => t('Confirm'),
    '#submit' => array(
      'prc_workflow_pre_submit_handler',
      'node_form_submit'
    ),
  );
  $form['actions']['cancel'] = array(
    '#markup' => l(t('Cancel'), 'node/'.$form['#node']->nid),
  );
}

/**
 * Implements hook_form_FORM_ID_alter()
 * @param $form
 * @param $form_state
 */
function prc_workflow_form_state_flow_events_revision_alter(&$form, &$form_state) {
  $form['#submit'][] = 'prc_workflow_events_submit';

  if ($form['event']['#value'] == 'denied') {
    // Changes before Approval for PRC-592 @timestamp (revision #)
    $title = $form_state['build_info']['args'][0]->title;
    $vid = $form_state['build_info']['args'][0]->vid;
    $new_title = t('Changes before Approval for @title (revision @vid)', array(
      '@title' => $title,
      '@vid' => $vid
    ));
    drupal_set_title($new_title);

    $form['event_comment']['#title'] = t('Message');

    $form['submit']['#value'] = t('Send Request');

    $form['instructions'] = array(
      '#markup' => t('Instructions: (to be added)'),
      '#prefix' => '<div class="instructions">',
      '#suffix' => '</div>',
      '#weight' => -1,
    );

  }
  else {
    //@todo: form title for rescind request
    $node = $form['node_revision']['#value'];
    $state_flow = $form['state_flow']['#value'];

    $vid = $node->vid;
    $node_title = $node->title;

    $event = $state_flow->get_event($form['event']['#value']);

    $state_key = $event->get_option('target');

    $options = $state_flow->get_states_options();
    $new_state = $options[$state_key]['label'];
    $new_title = "Transition $node_title (revision $vid) to \"$new_state\"";

    drupal_set_title($new_title);

    //Don't show the text area for other state changes (prc-873)
    $form['event_comment']['#type'] = 'hidden';
    $form['event_comment']['#required'] = FALSE;
    $event = $form['event']['#value'];
    $form['event_comment']['#value'] = 'Event: ' . $event;
  }
}

/**
 * Additional submit handler for revisions.
 *
 * @param $form
 * @param $form_state
 */
function prc_workflow_events_submit(&$form, &$form_state) {
  //Redirect to our content tab instead of the workflow pages
  $form_state['redirect'] = 'admin-content';
}

/**
 *
 */
function prc_workflow_pre_submit_handler($form, &$form_state) {
  //Check if the button pressed is save draft
  $state_flow = state_flow_load_state_machine($form['#node']);
  //Only require confirmation when published
  if($state_flow->get_current_state() === 'published') {
    if ($form_state['triggering_element']['#value'] == 'Save New Draft') {
      $form_state['display_confirmation'] = TRUE;
      $form_state['saved_values'] = $form_state['values'];
      $form_state['rebuild'] = TRUE;
    }
    if ($form_state['triggering_element']['#value'] == 'Confirm') {
      $form_state['values'] = $form_state['saved_values'];
    }
  }
}


/**
 * Handles submission of the form by workflow actions
 *
 * @param $form
 * @param $form_state
 */
function prc_workflow_submit_handler($form, &$form_state) {

  $node = $form['#node'];

  //Determine which button was pressed and fire the corresponding event
  if (!empty($node->vid)) {//skip if we are creating a new node

    //We put the event name in an id in the form alter, retrieve it
    $clicked = $form_state['clicked_button']['#attributes']['data-event'];

    $state_machine = state_flow_load_state_machine($node, TRUE);
    $events = $state_machine->get_all_events();

    foreach ($events as $key => $event) {
      if ($clicked == $key) {

        //Workaround having to do with this being action buttons on edit form
        if (isset($event['actual_event'])) {
          $key = $event['actual_event'];
          $event = $events[$event['actual_event']];
        }

        //Get the correct version of the node
        $state_to_fetch = $event['origin'];

        $node = prc_workflow_fetch_latest_node_version_by_state($node->nid, $state_to_fetch);

        //redirect to the confirmation form
        unset($_GET['destination']);
        $form_state['redirect'] = 'node/' . $node->nid . '/revisions/' . $node->vid . '/workflow/' . $key;
        continue;
      }
    }
  }
}

/**
 * Fetches the most recent node revision of a particular state
 *
 * @param $nid
 * @param $state
 * @return bool|mixed
 */
function prc_workflow_fetch_latest_node_version_by_state($nid, $state) {

  $vid = db_query("
    select nrs.vid from {node_revision_states} nrs
    where nrs.nid = :nid
      and nrs.state = :state
      and nrs.status = 1
    order by nrs.vid DESC limit 1",
    array(':nid' => $nid, ':state' => $state))->fetchField();

  return $vid ? node_load($nid, $vid, TRUE) : FALSE;
}

/**
 * A state machine guard callback to determine whether the user taking the action
 * is the owner of the corresponding node.
 *
 * @param $event
 */
function prc_workflow_user_owns_node($event, $node = NULL, $account = NULL) {
  if (!$node) {
    $machine = $event->get_machine();

    $node = $machine->get_object();
  }

  if (!$account) {
    global $user;
    $account = $user;
  }

  if ($node->uid === $account->uid) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_state_flow_event_fired()
 *
 * @param $node
 * @param $event_key
 * @param $uid
 * @param $log
 */
function prc_workflow_state_flow_event_fired($node, $event_key, $uid, $log) {
  $machine = state_flow_load_state_machine($node);

  switch ($event_key) {
    case 'approval_requested':
      prc_workflow_message('ready_for_review', $node);
      break;
    case 'rescind_request':
      prc_workflow_message('rescind_review_request', $node);
      break;
    case 'denied':
      prc_workflow_message('request_changes', $node);
      break;
    case 'unpublish':
      prc_workflow_message('unpublished_notice', $node);
      //We are firing this here because exiting doesn't necessarily mean unpublish
      $machine->on_exit_published();
      break;
    case 'update_published' :
    case 'republish' :
    case 'approved' :
      prc_workflow_message('published_notice', $node);
      break;
  }
}

/**
 * Helper function to create messages
 *
 * @param $message_type
 * @param $node
 */
function prc_workflow_message($message_type, $node) {
  global $user;

  $message = message_create($message_type);

  $wrapper = entity_metadata_wrapper('message', $message);

  $wrapper->field_node->set($node);


  if ($message_type == 'request_changes') {
    // The vid we need is that of the most recent history, not of the node that
    // was passed in, nor of the most recent vid
    $result = db_query('select vid from {node_revision_states_history}
      where nid = :nid order by nrshid DESC limit 1', array(':nid' => $node->nid))->fetchField();

    $wrapper->field_version_id->set($result);
  }

  $wrapper->field_user_ref->set($user);

  $wrapper->save();

  // This message type is associated with roles in prc_emails.
  _prc_emails_message_create($message, $node);
}

/**
 * Base status on the status of all active revisions rather than just the most
 * recent draft.
 *
 * @param $node
 */
function prc_workflow_reported_state($nid) {

  //Base reported state on the most recent draft rather than the most advanced draft
  //Get the active drafts
  $active_versions = db_query("
    select * from {node_revision_states} nrs
    where nrs.nid = :nid
      and nrs.status = 1 order by vid ASC",
    array(':nid' => $nid))->fetchAllAssoc('vid');

  //Check active drafts for any of the states our logic will require
  $active_published = NULL;
  $active_draft = NULL;
  $active_review = NULL;

  foreach ($active_versions as $vid => $revision) {
    switch ($revision->state) {
      case 'draft' :
        $active_draft = $vid;
        break;
      case 'published' :
        $active_published = $vid;
        break;
      case 'ready_for_review' :
        $active_review = $vid;
        break;
    }
  }

  if ($active_review) {
    $reported_state = 'ready_for_review';
  }
  elseif ($active_draft) {
    $reported_state = 'draft';
  }
  elseif ($active_published) {
    $reported_state = 'published';
  }

  return $reported_state;
}