<?php

/**
 * @file
 * Modifies the user edit form so that users that do have permission to administer users,
 * but do NOT have the administrator role (defined in the user_admin_role variable,
 * "administrator" for standard installations) are not allowed to give the administrator
 * role to users they edit or create.
 *
 * Pseudo-Behat tests
 * Given I am logged in as a user with the "Administer users" permissions
 * And I do not have the "administrator" role
 * When I edit a user
 * Then I do not see an "administrator" option

 * Given I am logged in as a user with the "Administer users" permissions
 * And I have the "administrator" role
 * When I edit a user
 * Then I see an "administrator" option
 */

/**
 * Implements hook_form_alter().
 */
function admin_role_restrict_form_alter(&$form, &$form_state, $form_id) {
  // Make sure this is a user edit form, and that the user_admin_role role actually exists
  // TODO: Fix this! Not happy about this, but the install profile messed with the rids.
  // We're just going with the name 'administrator' now.
  if (($form_id == 'user_profile_form' || $form_id == 'user_registration_form') && $user_admin_role = user_role_load_by_name('administrator')) {
    global $user;
    $user_is_admin = array_key_exists($user_admin_role->rid, $user->roles);

    if (!$user_is_admin) {
      unset($form['account']['roles']['#options'][$user_admin_role->rid]);
    }
  }
}
