<?php

/**
 * @file
 * Alters to login forms.
 */


/**
 * Implements hook_form_FORM_ID_alter
 *
 * Changes the display of the account username to the account full name
 *
 * @param $form
 * @param $form_state
 */
function prc_login_form_form_user_pass_reset_alter(&$form, &$form_state) {
  $orig_message = $form['message']['#markup'];
  $uid = $form_state['build_info']['args'][0];
  $account = user_load($uid);
  if ($account) {
    $account_name = $account->name;
    $w = entity_metadata_wrapper('user', $account);
    $fn = $w->field_first_name->value();
    $ln = $w->field_last_name->value();
    $new_name = $fn . ' ' . $ln;
    $new_message = str_replace($account_name, $new_name, $orig_message);
    $form['message']['#markup'] = $new_message;
  }
}

function prc_login_form_form_user_register_form_alter(&$form, &$form_state) {
  drupal_set_title('Create User Account to Join Partnership Resource Center');
}

/**
 * @param $form
 * @param $form_state
 */
function prc_login_form_form_user_login_block_alter(&$form, &$form_state) {
  // Are these really theming operations?
  // String substitution?
  // Well, anyway, we are replacing them per PRC-51 AC#4
  $replaces = array(
    'Request new password' => 'Forgot password?',
    'Create new account' => 'Join now!',
    '<a href="/user/register"' => 'Not registered yet? <a href="/user/register"',
  );

  foreach ($replaces as $replace => $with) {
    $links = str_replace($replace, $with, $form['links']['#markup']);
    $form['links']['#markup'] = $links;
  }

}

/**
 *  Implements hook_user_insert().
 */
function prc_login_form_user_insert(&$edit, $account, $category) {
  //TODO: Check that this user is self-registering and not coming through an invitation
  //_prc_login_form_add_role_to_user($account, 'Educator');
  // Get the rid from the roles table.
  $role_name = 'Educator';
  $roles = user_roles(TRUE);
  $rid = array_search($role_name, $roles);
  if ($rid != FALSE) {
    $new_role[$rid] = $role_name;
    $all_roles = $account->roles + $new_role; // Add new role to existing roles.
    $account->roles = $all_roles;
  }
  drupal_register_shutdown_function('_prc_login_form_user_restrict_single_role', $account);
}

function _prc_login_form_user_restrict_single_role($account) {
  $new_account = user_load($account->uid);
  $old_roles = $new_account->roles;
  $all_roles = user_roles(TRUE);

  // Creating an administrator should kill all the other roles
  $admin = array_search('administrator', $old_roles);
  // Every user gets authenticated user
  // If there is educator and there is anything else, remove educator
  $educator = array_search('Educator', $old_roles);

  $auth_user_rid = array_search('authenticated user', $all_roles);

  if ($admin) {
    $admin_rid = array_search('administrator', $all_roles);
    $old_roles = array(
      $admin_rid => 'administrator',
      $auth_user_rid => 'authenicated user',
    );
  } elseif ($educator) {
    $excludes = array('authenticated user', 'Educator');
    $save_role_name = '';
    $save_rid = 0;
    foreach($old_roles as $rid => $name) {
      if (!in_array($name, $excludes)) {
        $save_role_name = $name;
        $save_rid = $rid;
      }
    }
    if ($save_rid) {
      $old_roles[$educator] = 0;
    }
  }
    // Save user without Educator
    user_save($account, array('roles' => $old_roles));

}

/**
 * Add a role to a user.
 *
 * @param $user
 *   User object or user ID.
 * @param $role_name
 *   String value of role to be added.
 *
 * @see http_://drupal.org/node/28379#comment-4277052
 * @see http_://api.drupal.org/api/drupal/modules--user--user.module/function/user_save
 */
function _prc_login_form_add_role_to_user($user, $role_name) {
  // For convenience, we'll allow user ids as well as full user objects.
  if (is_numeric($user)) {
    $user = user_load($user);
  }
  // If the user doesn't already have the role, add the role to that user.
  $key = array_search($role_name, $user->roles);
  if ($key == FALSE) {
    // Get the rid from the roles table.
    $roles = user_roles(TRUE);
    $rid = array_search($role_name, $roles);
    if ($rid != FALSE) {
      $new_role[$rid] = $role_name;
      $all_roles = $user->roles + $new_role; // Add new role to existing roles.
      user_save($user, array('roles' => $all_roles));
    }
  }
}

