<?php

/**
 * @file
 * Allows users to add content to favorites lists
 */

/**
 *  Implements hook_menu().
 */
function prc_my_lists_menu() {
  // Display a node add form in ctools modal.
  $items = array();
  $items['favorites-list/%node/%ctools_js/add-to-list'] = array(
    'title' => 'Add to My Lists',
    'title callback' => 'check_plain',
    'page callback' => 'modal_add_to_list',
    'page arguments' => array(3, 2, 1),
    'access callback' => 'node_access',
    'access arguments' => array('create', 'favorites_list'),
    'description' => 'My Lists',
    'file' => 'prc_my_lists.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $items['favorites-list/%node/%ctools_js/create-list'] = array(
    'title' => 'Add to My Lists',
    'title callback' => 'check_plain',
    'page callback' => 'modal_add_a_list',
    'page arguments' => array(3, 2, 1),
    'access callback' => 'node_access',
    'access arguments' => array('create', 'favorites_list'),
    'description' => 'My Lists',
    'file' => 'prc_my_lists.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $items['digital_library_favorites_list/%ctools_js/%node'] = array(
    'type' => MENU_CALLBACK,
    'title' => t('Digital Library My Lists'),
    'description' => t('Digital Library Favorites List AJAX Panel selection'),
    'page callback' => 'prc_ajax_show_digital_library_favorites_list',
    'file' => 'prc_my_lists.ajax.inc',
    'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 *  Implements hook_permission().
 */
function prc_my_lists_permission() {
  $perms = array(
    'add to my lists' => array(
      'title' => t('Add to My Lists'),
      'description' => t('Add content to Favorites Lists'),
    ),
  );
  return $perms;
}


/**
 *  Implements hook_node_view().
 */
function prc_my_lists_node_view($node, $view_mode, $langcode) {
  global $user;
  if (user_access('add to my lists', $user)) {

    $listable_types = array(
      'digital_library_content' => array(
        'link_id' => 'prc_digital_library_add_to_favorites',
        'link_title' => 'Add to My Lists',
      ),
      'pd_course' => array(
        'link_id' => 'prc_pd_course_add_to_favorites',
        'link_title' => 'Add to My PD Lists',
      ),
    );

    if (array_key_exists($node->type, $listable_types)) {
      $link_id = $listable_types[$node->type]['link_id'];
      $link_title = $listable_types[$node->type]['link_title'];
      _prc_my_lists_add_to_lists_link($node, $link_title, $link_id);
    }
  }
}

/**
 * @param $node
 * @param $link_title
 * @param $link_id
 */
function _prc_my_lists_add_to_lists_link($node, $link_title, $link_id) {
  ctools_include('modal');
  ctools_modal_add_js();
  $nid = $node->nid;

  $links[$link_id] = array(
    'title' => t($link_title),
    'href' => "favorites-list/$nid/nojs/add-to-list",
    'attributes' => array(
      'title' => t($link_title),
      'class' => array('ctools-use-modal'),
    ),
  );

  $node->content['links'][$link_id] = array(
    '#theme' => 'links__node__favorites',
    '#links' => $links,
    '#attributes' => array('class' => array('links', 'inline')),
  );
}
