<?php

/**
 * @file
 * Alters to user edit forms.
 */

/**
 *  Implements hook_block_view_alter().
 */
function prc_search_block_view_alter(&$data, $block) {
  if ($block->module == 'search') {
    if (isset($data) && is_array($data) &&
        array_key_exists('content', $data) &&
        array_key_exists('search_block_form', $data['content'])) {
      // Adding placeholder text
      $data['content']['search_block_form']['#attributes']['placeholder'] = t('Search');
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function prc_search_form_search_form_alter(&$form, &$form_state) {

  // Adding placeholder text
  $form['basic']['keys']['#attributes']['placeholder'] = t('Search');

  // Here we are adding Search results for: criteria
  // if the user has performed a search
  $criteria = $form['basic']['keys']['#default_value'];
  if ($criteria) {
    $criteria = filter_xss($criteria, array());

    $criteria_markup = "<h2>Search results for: $criteria</h2>";

    $form['include_criteria'] = array(
      '#type' => 'markup',
      '#markup' => $criteria_markup,
    );
  }
}
