@api @course
Feature: PRC-368 Admin: Register LTI Course
  As a PRC Admin or Content Administrator (Curator)
  I want to edit an existing course,
  so that I can update the course attributes and course audience when needed.

  Acceptance Criteria:
  1.  In Course Management page, a new action Export shall be added to the Actions column
  2.  At click, it opens a popup or new page with the following attributes:
  a. Title- Export Course: '<Course Name>'
  b. Generate LTI Info button
  Clicking the Generate LTI Info button shall display that contains the following information for each course object (module/exam):
  URL:
  Key & Password: The system shall generate and provide a unique key generated by the system, along with a password


  Background:
    Given I am logged in as a user with the "Content Administrator (Curator)" role
    And I have no "PD Course" nodes
    And I am viewing my "PD Course" node with the title "PRC-349 AC2"
    And I am on "admin-course"
    When I click "Export"
    Then I should see the heading "LTI Course Registration" in the "content" region

  Scenario: AC2: Access the LTI Registration Form

    And I should see "Course Title: PRC-349 AC2"
    And I should see a "LTI Registration Name" field
    And I should see a "Generate LTI Info" button
    And I press the "Generate LTI Info" button
    Then I should see the error message containing "LTI Registration Name field is required."

  Scenario: AC3
    When I fill in "LTI Registration Name" with "PRC-386 Test Registration"
    Then I press the "Generate LTI Info" button
    Then I should see the heading "LTI Course Registration Confirmation"
    And I should see "LTI Registration Name: PRC-386 Test Registration"
    And I should see text matching "Key: *"
    And I should see text matching "Secret: *"
    And I should see text matching "LTI URL: *"
    And I should see "Custom Fields: (Each line below represents an individual module that should be linked from the remote system using the information above and the line's \"custom_destination\" setting below."