@api @footer @terms_of_use @prc-615 @prc-1254
Feature: PRC-615 Accessing Terms of Use
  As a user,
  I want to have access to PARCC Terms of Use when accessing PRC.

  Scenario: View ToU
    Given I am an anonymous user
    When I click "Terms of Use" in the "footer_copyright" region
    Then I should see the heading "Terms of Use"
    And I should see the text "Parcc Inc. Partnership Resource Center \(PRC\) Terms of Use \(ToU\)"
    And I should see the text "Effective Date"
    And I should see the text "September 18, 2015"
    And I should see the text "Current Version Date"
    And I should see the text "September 18, 2015"
    And I should see the text "Thank you for reviewing the terms and conditions for Parcc Inc.’s Partnership Resource Center \(PRC\)."
    And I should see the text "This ToU governs your use of the PRC and your use of the PRC indicates you explicitly agree to this ToU. This ToU also discloses Parcc Inc.’s information gathering and dissemination activities. Parcc Inc. is committed to protecting your privacy and the security of the information you entrust with us and has developed this ToU for protecting and informing you."
    And I should see the text "Parcc Inc. is the project management partner for the PARCC consortium of states and oversees the development of the PARCC assessment system and related tools, supports the governance and decision-making of consortium states, provides day-to-day management of the project, and develops and maintains plans for the consortium’s long-term sustainability."
    And I should see the text "The PRC supports four outcomes; deepening assessment literacy, connecting instructional and assessment practices, building practitioner capacity, and evaluating the quality of assessment resources."
    And I should see the text "TERMS"
    And I should see the text "You are of legal age in your jurisdiction to use this website."
    And I should see the text "Use of any content from this site is subject to all copyright laws. Parcc Inc. holds the copyright to all content on the PRC except for user-generated or submitted content and that content under license from third parties as noted. You may not use the content or resources for non-educational or commercial activities without express written consent of Parcc Inc. All use of content or resources used by you from the PRC must be unedited and directly attributed."
    And I should see the text "Most resources on the PRC are freely available to non-registered users for educational non-commercial activities. However, some resources will require a username and password. Additionally, some resources are limited to PARCC consortia members requiring both logging and authentication through a membership code. If you are from a PARCC consortia member organization or subscribing entity, please contact your representative for additional information on accessing all the content and resources on PRC. If you delete your account on the PRC, the data your account generated will not necessarily be deleted."
    And I should see the text "The PRC uses cookie based analytics to track and monitor use. Cookies are enabled throughout the PRC and Parcc Inc. encourages you to leave your cookies enabled to fully utilize this site. They are used by Parcc Inc. to manage access to content and resources, improve the performance of the website, inform the creation of new resources, and to track the use of licensed resources available. Parcc Inc. at its discretion determines what data to collect including, but not limited to, IP address, browser information, locality, and network."
    And I should see the text "Parcc Inc. will retain, at its discretion, the data generated by the cookies to study long-term website use trends and to evaluate the efficacy of the content and resources on the PRC."
    And I should see the text "Parcc Inc. will not sell or share your personal information or the aggregate data with third parties for commercial or non-educational activities."
    And I should see the text "Parcc Inc. may contact you via email to share news, information, or updates on the PRC or other Parcc Inc. programs that may be of interest to you."
    And I should see the text "Parcc Inc. reserves the right to amend this ToU at any time without notification to the users of the PRC. However, Parcc Inc. will notify users of material changes to the best of its ability. If changes to this policy are made, your continued use is acceptance of the amendments made."
    And I should see the text "For any legal issues arising from the use of this website, its content or its resource, the jurisdiction that will be used for applicable governance is that of Washington D.C."

  Scenario: PRC-1254 - No submitted by author or date
    Given I am an anonymous user
    When I click "Terms of Use" in the "footer_copyright" region
    Then I should not see the text "Submitted by"