@api @trt @structured @district
Feature: PRC-837 District Name - Add Form
  As a District Admin,
  I want to be able to add my district name
  so I can set up my district readiness page.

  Acceptance Criteria
  Given that I am logged in as a District Admin
  And I am on the Technology Readiness page
  And I have not added my district name
  When I click the Add District link
  Then I see the Add District page that has:
  Page header
  Add District
  Overview copy
  Instructions to District Admin to add district, which will allow results generated by School Admin to be reported to the district.
  Form fields
  Label: District Name
  Type: Text field
  Required: Yes
  Submit button

  Scenario: Non-District Admin can't add district
    Given I am logged in as a user with the "Educator" role
    And I have no "District" nodes
    When I visit "technology-readiness"
    Then I should not see the link "Add District"

  Scenario: Add new district - District Admin
    Given I am logged in as a user with the "District Admin" role
    And I have no "District" nodes
    And I visit "technology-readiness"
    When I click "Add District"
    Then I should see the heading "Add District"
    And I should see the text "Instructions to District Admin to add district, which will allow results generated by School Admin to be reported to the district."
    And I should see the text "District Name \*"
    And I should see a "Submit" button
