<?php

/**
 * @file
 * Alters to user edit forms.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 * @param $form
 * @param $form_state
 */
function prc_user_edit_form_form_user_profile_form_alter(&$form, &$form_state) {
  global $user;
  if (!array_search('administrator', $user->roles)) {
    $form['account']['mail']['#title'] = 'E-mail';
    $form['picture']['#access'] = FALSE;
    $form['account']['name']['#access'] = FALSE;
    $form['og_user_node']['#access'] = FALSE;
  }

  $w = entity_metadata_wrapper('user', $form['#user']);
  $first = $w->field_first_name->value();
  $last = $w->field_last_name->value();
  $uid = $w->uid->value();
  $title = "$first $last ($uid)";
  drupal_set_title($title);
}
