<?php

/**
 * @file
 * Alters to user edit forms.
 */

/**
 * Implements hook_form_alter().
 * @param $form
 * @param $form_state
 */
function user_single_role_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_profile_form' || $form_id == 'user_registration_form') {
    // We are generating a fake roles field so that we don't have to make any changes
    // to the actual role field.
    $form['faux_roles'] = $form['account']['roles'];
    $form['faux_roles']['#type'] = 'radios';
    $form['faux_roles']['#required'] = TRUE;
    unset($form['faux_roles'][2]);

    foreach ($form['account']['roles']['#default_value'] as $role_key => $selected) {
      // Don't bother with auth user - every user has to have it and we'll set it by default in submit
      if ($selected != 2) {
        //unset($form['faux_roles']['#default_value'][$role_key]);
        $form['faux_roles'][$selected]['#default_value'] = TRUE;
      }
    }

    $form['account']['roles']['#access'] = FALSE; // Hide the normal roles checkboxes

    $form['#submit'][] = 'user_single_role_form_user_profile_form_submit';
  }
}

function user_single_role_form_user_profile_form_submit(&$form, &$form_state) {
  $selected_role = $form_state['values']['faux_roles'];
  $uid = $form_state['user']->uid;
  $account = user_load($uid);
  foreach ($account->roles as $rid => $value) {
    if ($rid != 2 && $rid != $selected_role) {
      $account->roles[$rid] = 0;
    }
    else {
      $account->roles[$rid] = $rid;
    }
  }
  $all_roles = $account->roles;
  user_save($account, array('roles' => $all_roles));
}
