<?php


/**
 * Implements hook_form_alter().
 * @param $form
 * @param $form_state
 */
function prc_digital_library_form_form_digital_library_content_node_form_alter(&$form, &$form_state) {

  // Expand fieldsets with existing content
  $w = entity_metadata_wrapper('node', $form_state['node']);

  $expand = array();

  $expand['group_attach_a_file'] = ($w->field_document->value()) ? 'collapsible': 'collapsed';
  $expand['group_link_to_url'] = ($w->field_link_to_a_url->value()) ? 'collapsible' : 'collapsed';
  if ($w->field_grade_level->value() ||
    $w->field_subject->value() ||
    $w->field_media_type->value() ||
    $w->field_genre->value() ) {
    $expand['group_metadata'] = 'collapsible';
  }
  else {
    $expand['group_metadata'] = 'collapsed';
  }

  foreach ($expand as $g=>$e) {
    if ($e) {
      $form['#fieldgroups'][$g]->format_settings['formatter'] = $e;
    }
  }
}