<?php
/**
 * @file
 * PRC Technology Readiness Tool module code.
 */

function prc_trt_form_eck__entity__form_add_prc_trt_system_check_alter(&$form, &$form_state) {
  $form['actions']['submit']['#value'] = t('Submit');

  $hide_fields = array(
    'field_monitor_color_depth',
    'field_screen_resolution_width',
    'field_screen_resolution_height',
    'field_browser',
    'field_browser_version',
    'field_browser_cookies_enabled',
    'field_browser_javascript_enabled',
    'field_browser_images_enabled',
  );

  foreach ($hide_fields as $hide_field) {
    $form[$hide_field]['#access'] = FALSE;
  }

  $form['faux_browser'] = array(
    '#type' => 'hidden'
  );
  $form['faux_javascript'] = array(
    '#type' => 'hidden'
  );
  $form['faux_cookies'] = array(
    '#type' => 'hidden'
  );
  $form['faux_images'] = array(
    '#type' => 'hidden'
  );
  $form['faux_monitor_color_depth'] = array(
    '#type' => 'hidden'
  );
  $form['faux_screen_resolution_width'] = array(
    '#type' => 'hidden'
  );
  $form['faux_screen_resolution_height'] = array(
    '#type' => 'hidden'
  );

  drupal_add_js(drupal_get_path('module', 'prc_trt') . '/prc_trt.js');

  $form['#validate'][] = 'prc_trt_form_eck__entity__form_add_prc_trt_system_check_validate';
}

function prc_trt_form_eck__entity__form_add_prc_trt_system_check_validate(&$form, &$form_state) {
  $my_browser = 'other';
  // Set field_browser's value to show what browser the user is in.
  if (array_key_exists('faux_browser', $form_state['input']) && $form_state['input']['faux_browser']) {
    $my_browser = $form_state['input']['faux_browser'];
    $b = explode(' ', $my_browser);
    $browser_type = $b[0];
    $browser_version = $b[1];
  } elseif (isset($_SERVER['HTTP_USER_AGENT'])) {
    $agent = strtolower($_SERVER['HTTP_USER_AGENT']);
    $browser = browserclass_check_browser($agent);
    if (is_array($browser) && count($browser)) {
      $my_browser = array_pop($browser);
      $browser_type = array_pop($browser);
      $browser_version = str_replace($browser_type, '', $my_browser);
    }
  }
  form_set_value($form['field_browser'], array(LANGUAGE_NONE => array(0 => array('value' => $browser_type))), $form_state);
  form_set_value($form['field_browser_version'], array(LANGUAGE_NONE => array(0 => array('value' => $browser_version))), $form_state);

  $javascript = $form_state['input']['faux_javascript'] === 'true' ? 1 : 0;
  form_set_value($form['field_browser_javascript_enabled'], array(LANGUAGE_NONE => array(0 => array('value' => $javascript))), $form_state);

  $cookies = $form_state['input']['faux_cookies'] === 'true' ? 1 : 0;
  form_set_value($form['field_browser_cookies_enabled'], array(LANGUAGE_NONE => array(0 => array('value' => $cookies))), $form_state);

  $images = $form_state['input']['faux_images'] === 'true' ? 1 : 0;
  form_set_value($form['field_browser_images_enabled'], array(LANGUAGE_NONE => array(0 => array('value' => $images))), $form_state);

  $monitor_color_depth = $form_state['input']['faux_monitor_color_depth'];
  form_set_value($form['field_monitor_color_depth'], array(LANGUAGE_NONE => array(0 => array('value' => $monitor_color_depth))), $form_state);

  $res_w = $form_state['input']['faux_screen_resolution_width'];
  form_set_value($form['field_screen_resolution_width'], array(LANGUAGE_NONE => array(0 => array('value' => $res_w))), $form_state);

  $res_h = $form_state['input']['faux_screen_resolution_height'];
  form_set_value($form['field_screen_resolution_height'], array(LANGUAGE_NONE => array(0 => array('value' => $res_h))), $form_state);

}

/**
 * Implements hook_field_extra_fields().
 */
function prc_trt_field_extra_fields() {
  $extra['prc_trt']['system_check']['display'] = array(
    'overall_pass' => array(
      'label' => t('System Check Results'),
      'description' => t('Did the system check pass?'),
      'weight' => 11,
    ),
    'operating_system_pass' => array(
      'label' => t('Operating system: Results'),
      'description' => t('Did operating system pass?'),
      'weight' => 12,
    ),
    'monitor_size_pass' => array(
      'label' => t('Monitor size: Results'),
      'description' => t('Did monitor size pass?'),
      'weight' => 13,
    ),
    'monitor_color_depth_pass' => array(
      'label' => t('Monitor color depth: Results'),
      'description' => t('Did monitor color depth pass?'),
      'weight' => 14,
    ),
    'screen_resolution_pass' => array(
      'label' => t('Screen resolution: Results'),
      'description' => t('Did screen resolution pass?'),
      'weight' => 15,
    ),
    'processor_pass' => array(
      'label' => t('Processor speed: Results'),
      'description' => t('Did processor pass?'),
      'weight' => 16,
    ),
    'ram_pass' => array(
      'label' => t('RAM: Results'),
      'description' => t('Did RAM pass?'),
      'weight' => 17,
    ),
    'browser_pass' => array(
      'label' => t('Browser: Results'),
      'description' => t('Did browser pass?'),
      'weight' => 18,
    ),
    'cookies_pass' => array(
      'label' => t('Cookies: Results'),
      'description' => t('Did cookies pass?'),
      'weight' => 19,
    ),
    'javascript_pass' => array(
      'label' => t('Javascript: Results'),
      'description' => t('Did Javascript pass?'),
      'weight' => 20,
    ),
    'images_pass' => array(
      'label' => t('Images: Results'),
      'description' => t('Did images pass?'),
      'weight' => 21,
    ),
  );
  return $extra;
}

/**
 * Implements hook_entity_view().
 */
function prc_trt_entity_view($entity, $type, $view_mode, $langcode) {
  if ($type == 'prc_trt' && $entity->type == 'system_check') {
    drupal_set_title(t('System Check'));
    $w = entity_metadata_wrapper('prc_trt', $entity);
    $os = $w->field_operating_system->value();
    $size = $w->field_monitor_size->value();
    $size_pass = $size >= 9.7;
    $depth = $w->field_monitor_color_depth->value();
    $depth_pass = $depth >= 16;
    $resw = $w->field_screen_resolution_width->value();
    $resw_pass = $resw >= 1024;
    $resh = $w->field_screen_resolution_height->value();
    $resh_pass = $resh >= 768;
    $processor = $w->field_processor_speed->value();
    $processor_pass = $processor >= 1;
    $ram = $w->field_ram->value();
    $ram_pass = strpos(strtolower($ram), 'mb') === FALSE;
    $browser = $w->field_browser->value();

    $cookies_pass = $w->field_browser_cookies_enabled->value();
    $js_pass = $w->field_browser_javascript_enabled->value();
    $images_pass = $w->field_browser_images_enabled->value();

    $all_pass = $size_pass && $depth_pass && $resw_pass && $resh_pass && $processor_pass && $ram_pass && $cookies_pass && $js_pass && $images_pass;

    $entity->content['overall_pass'] = array(
      '#type' => 'item',
      '#title' => t('System Check Results:'),
      '#markup' => $all_pass ? t('Passed') : t('Failed'),
    );
    $entity->content['operating_system_pass'] = array(
      '#type' => 'item',
      '#title' => t('Operating system Results:'),
      '#markup' => $js_pass ? 'Pass' : 'Fail',
    );
    $entity->content['monitor_size_pass'] = array(
      '#type' => 'item',
      '#title' => t('Monitor size Results:'),
      '#markup' => $size_pass ? 'Pass' : 'Fail',
    );
    $entity->content['monitor_color_depth_pass'] = array(
      '#type' => 'item',
      '#title' => t('Monitor color depth Results:'),
      '#markup' => $depth_pass ? 'Pass' : 'Fail',
    );
    $entity->content['screen_resolution_pass'] = array(
      '#type' => 'item',
      '#title' => t('Screen resolution Results:'),
      '#markup' => $resh_pass && $resw_pass ? 'Pass' : 'Fail',
    );
    $entity->content['processor_pass'] = array(
      '#type' => 'item',
      '#title' => t('Processor speed Results:'),
      '#markup' => $processor_pass ? 'Pass' : 'Fail',
    );
    $entity->content['ram_pass'] = array(
      '#type' => 'item',
      '#title' => t('RAM Results:'),
      '#markup' => $ram_pass ? 'Pass' : 'Fail',
    );
    $entity->content['browser_pass'] = array(
      '#type' => 'item',
      '#title' => t('Browser Results:'),
      '#markup' => $js_pass ? 'Pass' : 'Fail',
    );
    $entity->content['cookies_pass'] = array(
      '#type' => 'item',
      '#title' => t('Cookies Results:'),
      '#markup' => $cookies_pass ? 'Pass' : 'Fail',
    );
    $entity->content['javascript_pass'] = array(
      '#type' => 'item',
      '#title' => t('Javascript Results:'),
      '#markup' => $js_pass ? 'Pass' : 'Fail',
    );
    $entity->content['images_pass'] = array(
      '#type' => 'item',
      '#title' => t('Images Results:'),
      '#markup' => $images_pass ? 'Pass' : 'Fail',
    );
  }
}