<?php
/**
 * @file
 * Menu hooks and functions supporting the PRC menus.
 */

/**
 * Implements hook_menu()
 */
function prc_menu_links_menu() {
  $items['prc/admin'] = array(
    'title' => 'PRC Admin',
    'page callback' => 'prc_menu_links_prc_admin',
    'access callback' => 'prc_menu_links_is_prc_admin',
  );
  return $items;
}

/**
 * Access callback for prc/admin menu hook
 */
function prc_menu_links_is_prc_admin() {
  return user_access('create digital_library_content content') || user_access('administer course') || user_access('administer users');
}

/**
 * Page callback for prc/admin menu hook
 */
function prc_menu_links_prc_admin() {
  $menuItems = menu_tree_page_data('main-menu');
  foreach($menuItems as $key => $m) {
    // Check current active menu
    if ($m['link']['in_active_trail'] && $menuItems [$key]['below']) {
      $menu = menu_tree_output($menuItems [$key]['below']);
    }
  }
  // If the user sees any menu items under admin, display the admin sub menu
  if (isset($menu)) {
    return $menu;
  }
  // Users who don't have access to admin sub menu items shouldn't have permission
  // to see this page in the first place, but just in case...
  else {
    return MENU_ACCESS_DENIED;
  }
}
